project_id = "bhcnvdlezwudxywrknru"

[functions.seed-test-users]
verify_jwt = true

[functions.auth-with-rate-limit]
verify_jwt = false

[functions.pre-register-gym-owner]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.create-user-account]
verify_jwt = false

[functions.seed-super-admin]
verify_jwt = false
